cluster:
  nodes:
    - node_id: node1
      raft_addr: 127.0.0.1:28001
      http_addr: 127.0.0.1:29001
      raft_dir: ./raft/node1
      db_path: ./data/node1.db
      bootstrap: true

    - node_id: node2
      raft_addr: 127.0.0.1:28002
      http_addr: 127.0.0.1:29002
      raft_dir: ./raft/node2
      db_path: ./data/node2.db
      bootstrap: false
      join_addr: 127.0.0.1:29001

    - node_id: node3
      raft_addr: 127.0.0.1:28003
      http_addr: 127.0.0.1:29003
      raft_dir: ./raft/node3
      db_path: ./data/node3.db
      bootstrap: false
      join_addr: 127.0.0.1:29001

common:
  raft_timeout: 10s
  snapshot_interval: 30s
  snapshot_threshold: 1000
